stages:
  - Build
  - Test
  # - Deploy

build:
  stage: Build
  tags:
    - shell
  script:
    - mvn compile
  allow_failure: false

unittest:
  stage: Test
  tags:
    - shell
  script:
    - mvn test
  allow_failure: false
  artifacts:
    paths:
      - target/site/jacoco/

pages:
  stage: DeployPages
  tags:
    - shell
  dependencies:
    - unittest
  script:
    # First transfer generated testcoverage
   - mkdir public
   - mv target/site/jacoco public/jacoco/
    # Generate javadoc and move to site after
   - mvn javadoc:javadoc
   - mv target/site/apidocs public/javadoc/
  artifacts:
    paths:
      - public

# deploy:
#   stage: Deploy
#   tags:
#     - shell
#   script:
#     - echo "deploy"
#     - exit 1
#   allow_failure: true
