stages:
  - Build
  - Test
  - Deploy

build:
  stage: Build
  tags:
    - shell
  script:
    - mvn compile
  allow_failure: false

unittest:
  stage: Test
  tags:
    - shell
  script:
    - mvn test
  allow_failure: false

deploy:
  stage: Deploy
  tags:
    - shell
  script:
    - echo "deploy"
    - exit 1
  allow_failure: true
