stages:
  - Build
  - Test
  - DeployPages
  - BuildPackage

build:
  stage: Build
  tags:
    - shell
  script:
    - need java
    - mvn compile
  allow_failure: false

unittest:
  stage: Test
  tags:
    - shell
  script:
    - need java
    - mvn test
  allow_failure: false
  artifacts:
    paths:
      - target/site/jacoco/

pages:
  stage: DeployPages
  # Run this stage only on the master branch.
  only:
    - master
  tags:
    - shell
  dependencies:
    - unittest
  script:
    - need java
    # First transfer generated testcoverage
    - mkdir public
    - mv target/site/jacoco public/jacoco/
    # Generate javadoc and move to site after
    - mvn javadoc:javadoc
    - mv target/site/apidocs public/javadoc/
  artifacts:
    paths:
      - public

package:
  stage: BuildPackage
  tags:
    - shell
  script:
    - need java
    - mvn clean package
  artifacts:
    paths:
      # Only add the full mission-control jar wildcard the version
      - target/mission-control-*.jar