# Author: Nathan Duckett

stages:
  - Build
  - Test
  - DeployPages
  - BuildPackage

# Define script to build keys.json file.
.build_keys: &build_keys
  - |
    cat > src/main/resources/keys.json << EOF
    {
      "weather": $weather_api_key,
      "maps": $map_api_key
    }
    EOF

.build_windows_keys: &build_windows_keys
  - |
    $KeysContent = @{
      weather=$env:weather_api_key
      maps=$env:map_api_key
    }
  - $KeysContent | ConvertTo-Json | Set-Content ./src/main/resources/keys.json

build:
  stage: Build
  tags:
    - shell
  script:
    - mvn compile
  allow_failure: false

unittest:
  stage: Test
  tags:
    - shell
  before_script:
    - *build_keys
  script:
    - mvn test
  allow_failure: false
  artifacts:
    paths:
      - target/site/jacoco/

unittest_windows:
  stage: Test
  tags:
    - nathan
    - windows
  before_script:
    - *build_windows_keys
  script:
    - mvn test

pages:
  stage: DeployPages
  # Run this stage only on the master branch.
  only:
    - master
  tags:
    - shell
  dependencies:
    - unittest
  script:
    # First transfer generated testcoverage
    - mkdir public
    - mv target/site/jacoco public/jacoco/
    # Generate javadoc and move to site after
    - mvn javadoc:javadoc
    - mv target/site/apidocs public/javadoc/
  artifacts:
    paths:
      - public

package:
  stage: BuildPackage
  tags:
    - shell
  before_script:
    - *build_keys
  script:
    - mvn clean package
  artifacts:
    paths:
      # Only add the full mission-control jar wildcard the version
      - target/mission-control-*.jar

package_windows:
  stage: BuildPackage
  tags:
    - nathan
    - windows
  before_script:
    - *build_windows_keys
  script:
    - mvn clean package
  artifacts:
    paths:
      # Only add the full mission-control jar wildcard the version
      - ./target/mission-control-*.jar